id: P003151
initial_creation_type: ocr
source_metadata:
  id: bdr:W1KG16948
  title: དུས་རབས་གསར་པའི་རིག་གཞུང་གླེང་སྟེགས།
  author: ''
  volumes:
    46bd5b8d35dc40f8bb942dfe1122cad7:
      image_group_id: I1KG18452
      title: ''
      volume_number: 1
      total_pages: 346
